### ISSUE TITLE
2 years old

### ISSUE THREAD

**Issue by yratof** [elliotcondon/live-edit#13]
Aloha Elliot!

I'm looking at tis repo and thinking, mmm, thats a tasty burger 

![image](http://i.imgur.com/ZQ4I7vr.gif)

However, 2 years since it's been touched. Is this still compatible with the latest of the latest ACF?

**Comment by elliotcondon** [comment]
Hi @yratof 

Yep, live edit still works, but has been slightly abandoned.

I hope to pick it back up and improve on it soon.
