### ISSUE TITLE
Version 5 breaks page

### ISSUE THREAD

**Issue by Martin-DKK** [elliotcondon/live-edit#16]
Is there  a different way to activate version 5 than 4 as 4 works but 5 breaks the page.

	<div <?php live_edit('rejse_information'); ?>>
	<p></p>
	</div>

Thanks

**Comment by elliotcondon** [comment]
Hi @Martin-DKK 

Can you please enable DEBUG_MODE in your wp-config.php file, reload the page and report back with the PHP error that breaks the HTML?

**Comment by Martin-DKK** [comment]
Hi @elliotcondon,

Thank you for your reply, love the functionality of the plugin. I can see that the methods in ver. 5 is more up todate, but it breaks the page. 

This is the PHP error:

Fatal error: Uncaught Error: Call to undefined function acf_get_valid_post_id() in /Applications/MAMP/htdocs/Wordpress/wp-content/plugins/live-edit/live-edit-v5.php:399 Stack trace: #0 /Applications/MAMP/htdocs/Wordpress/wp-content/themes/sahifa-child/template-wiki.php(33): live_edit('rejse_informati...') #1 /Applications/MAMP/htdocs/Wordpress/wp-includes/template-loader.php(75): include('/Applications/M...') #2 /Applications/MAMP/htdocs/Wordpress/wp-blog-header.php(19): require_once('/Applications/M...') #3 /Applications/MAMP/htdocs/Wordpress/index.php(17): require('/Applications/M...') #4 {main} thrown in /Applications/MAMP/htdocs/Wordpress/wp-content/plugins/live-edit/live-edit-v5.php on line 399

Any fix for this?

**Comment by Martin-DKK** [comment]
Maybe worth to mention that i am activating Live-Edit from an template in my child theme.

**Comment by elliotcondon** [comment]
Hi @Martin-DKK 

Thanks for the reply. Your PHP error suggests that ACF PRO is not available:
Call to undefined function acf_get_valid_post_id()

Are you sure that ACF PRO is active?
Are you calling the live_edit() function somehow before plugins are loaded?

**Comment by Martin-DKK** [comment]
That is correct I am using the free version of ACF. Do i have to use the pro with live edit and what is the benefit?

**Comment by elliotcondon** [comment]
Hi @Martin-DKK 

Thanks for the reply.

Your error shows that Live Edit is loading in the 'v5' class which will only work with ACF PRO (v5).
The Live Edit plugin will work with both free (v4) and PRO (v5), however, it seems that the logic to determine which class gets loaded is being tricked.

Can you please debug the main live-edit.php file (very basic logic) and find out why the $version variable is set to 5 instead of 4?

**Comment by Martin-DKK** [comment]
Ohh okay i did that myself in the live-edit.php just to test it out. What is the gain of changing to pro and version 5

**Comment by elliotcondon** [comment]
ACF PRO is a full 2 years of extra development! http://advancedcustomfields.com/pro/
