### ISSUE TITLE
Uncaught ReferenceError: live_edit is not defined

### ISSUE THREAD

**Issue by rowphant** [elliotcondon/live-edit#9]
Hey there!

First: Great work with the ACF!
I just tried to get Live Edit to work but without success. Everytime I load the page there is just a note which says: "Uncaught ReferenceError: live_edit is not defined"

Any idea what this causes?

**Comment by elliotcondon** [comment]
Hi @rowphant 

Is this a JS or PHP error?
Is there any more to the error (such as file/line number)?
What code in your template can you add/remove to toggle the error?

**Comment by rowphant** [comment]
Hi @elliotcondon 

it was a php error. But this error was caused by myself. Just forgot to set the ***<?php wp_head(); ?>*** in the head tag of my template, so no plugin scripts were loaded.

Now it works like a charm! :)

**Comment by elliotcondon** [comment]
Thanks @rowphant 

Glad you got it working
